set_property PACKAGE_PIN L19 [get_ports {andGate_A[1]}]
set_property PACKAGE_PIN L20 [get_ports {andGate_A[0]}]
set_property PACKAGE_PIN L13 [get_ports andGate_Z]
set_property IOSTANDARD LVCMOS33 [get_ports {andGate_A[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {andGate_A[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports andGate_Z]
