set_property PACKAGE_PIN L20 [get_ports {andGate_A[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {andGate_A[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {andGate_A[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {andGate_Z[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {andGate_Z[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {andGate_Z[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {andGate_Z[0]}]

set_property PACKAGE_PIN K13 [get_ports {andGate_Z[3]}]
set_property PACKAGE_PIN K14 [get_ports {andGate_Z[2]}]
set_property PACKAGE_PIN M13 [get_ports {andGate_Z[1]}]
set_property PACKAGE_PIN L13 [get_ports {andGate_Z[0]}]
set_property PACKAGE_PIN J17 [get_ports {andGate_A[3]}]
set_property PACKAGE_PIN K17 [get_ports {andGate_A[2]}]
set_property PACKAGE_PIN L19 [get_ports {andGate_A[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {andGate_A[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {andGate_A[2]}]
